# Generated by Django 2.0.5 on 2018-06-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180612_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Zip Code'),
        ),
    ]
