# Generated by Django 2.0.5 on 2018-06-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180617_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='User',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Address'),
        ),
    ]
