# Generated by Django 2.0.7 on 2018-07-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_userowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bluetooth_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
